// GENERATED FILE - DO NOT EDIT
// This file is generated by tool/fetch_job_boards.dart

/// ジョブボードデータのJSON文字列
const String jobBoardsDataJson = r'''
[
  {
    "id": 1,
    "url": "https://job.persona-ats.com/ja/assign/jobs?filters=zmnNB_H2Q52r7D9fUwEQ6A",
    "alt_text": "株式会社アサインのジョブボード",
    "image_url": "https://2025-bucket.flutterkaigi.jp/job-boards/assign.png"
  },
  {
    "id": 2,
    "url": "https://hrmos.co/pages/cyberagent-group",
    "alt_text": "サイバーエージェント",
    "image_url": "https://2025-bucket.flutterkaigi.jp/job-boards/cyberagent.png"
  },
  {
    "id": 3,
    "url": "https://corporate.iiba.space/career",
    "alt_text": "株式会社iibaの採用ページ\nhttps://corporate.iiba.space/career",
    "image_url": "https://2025-bucket.flutterkaigi.jp/job-boards/iiba.png"
  },
  {
    "id": 4,
    "url": "https://hrmos.co/pages/simplex/jobs/60000001",
    "alt_text": "シンプレクス株式会社",
    "image_url": "https://2025-bucket.flutterkaigi.jp/job-boards/simplex.png"
  },
  {
    "id": 5,
    "url": "https://magicpod.com/corporate/recruit/",
    "alt_text": "株式会社MagicPod",
    "image_url": "https://2025-bucket.flutterkaigi.jp/job-boards/magicpod.png"
  },
  {
    "id": 6,
    "url": "https://hrmos.co/pages/zozo/jobs/1809846973241688329",
    "alt_text": "ZOZO, Inc. / ZOZOマッチ",
    "image_url": "https://2025-bucket.flutterkaigi.jp/job-boards/zozo.png"
  },
  {
    "id": 7,
    "url": "https://genda.jp/careers/",
    "alt_text": "株式会社GENDA 採用情報",
    "image_url": "https://2025-bucket.flutterkaigi.jp/job-boards/genda.png"
  },
  {
    "id": 8,
    "url": "https://jobs.m3.com/engineer/",
    "alt_text": "M3 エンジニアリンググループ : We're App Developers!",
    "image_url": "https://2025-bucket.flutterkaigi.jp/job-boards/m3.png"
  },
  {
    "id": 9,
    "url": "https://recruit.linc-well.com/engineer",
    "alt_text": "株式会社Linc'well 最高の医療体験を作りたい Flutter エンジニア募集",
    "image_url": "https://2025-bucket.flutterkaigi.jp/job-boards/lincwell.png"
  },
  {
    "id": 10,
    "url": "https://youtrust.jp/companies/youtrust",
    "alt_text": "YOUTRUST",
    "image_url": "https://2025-bucket.flutterkaigi.jp/job-boards/youtrust.png"
  },
  {
    "id": 11,
    "url": "https://www.team-lab.com/recruit/career/flutter/",
    "alt_text": "チームラボ Flutterエンジニア積極採用中！",
    "image_url": "https://2025-bucket.flutterkaigi.jp/job-boards/teamlab.png"
  },
  {
    "id": 12,
    "url": "https://recruit.soda-inc.jp/",
    "alt_text": "株式会社SODA",
    "image_url": "https://2025-bucket.flutterkaigi.jp/job-boards/soda.png"
  },
  {
    "id": 13,
    "url": "https://www.hacomono.co.jp/recruit/engineer/",
    "alt_text": "株式会社hacomono",
    "image_url": "https://2025-bucket.flutterkaigi.jp/job-boards/hacomono.png"
  }
]
''';
