// GENERATED FILE - DO NOT EDIT
// This file is generated by tool/fetch_staffs.dart

/// スタッフメンバーデータのJSON文字列
const String staffsDataJson = r'''
[
  {
    "id": "019a5472-c610-7f2d-a8af-438d41134742",
    "name": "asuka",
    "icon_name": "007200fc-8cdf-ec09-6184-3ec9c16014c5.webp",
    "icon_url": "https://2025-bucket.flutterkaigi.jp/staff-members/007200fc-8cdf-ec09-6184-3ec9c16014c5.webp",
    "greeting": "I □ Flutter",
    "sns_links": [
      {
        "type": "x",
        "value": "a_skua"
      },
      {
        "type": "github",
        "value": "a-skua"
      }
    ]
  },
  {
    "id": "019a5472-c610-7969-8c74-541a19fb6b21",
    "name": "CardsEditor",
    "icon_name": "6696bd31-1184-cccf-694c-35a73dbe99c8.webp",
    "icon_url": "https://2025-bucket.flutterkaigi.jp/staff-members/6696bd31-1184-cccf-694c-35a73dbe99c8.webp",
    "greeting": null,
    "sns_links": [
      {
        "type": "x",
        "value": "cardseditor"
      },
      {
        "type": "github",
        "value": "cardseditor"
      }
    ]
  },
  {
    "id": "019a5472-c610-7dcc-b01e-79fb2c391491",
    "name": "ENDO Takumi",
    "icon_name": "ca3e78a7-8afd-4e92-bb90-77b0878c3348.webp",
    "icon_url": "https://2025-bucket.flutterkaigi.jp/staff-members/ca3e78a7-8afd-4e92-bb90-77b0878c3348.webp",
    "greeting": null,
    "sns_links": [
      {
        "type": "other",
        "value": "https://endotakumi.github.io/"
      },
      {
        "type": "note",
        "value": "endo_takumi"
      },
      {
        "type": "zenn",
        "value": "endotakumi"
      },
      {
        "type": "qiita",
        "value": "ENDOTAKUMI"
      },
      {
        "type": "medium",
        "value": "endo.takumi.info"
      },
      {
        "type": "x",
        "value": "endotakumi_dev"
      },
      {
        "type": "github",
        "value": "ENDOTAKUMI"
      }
    ]
  },
  {
    "id": "019a5472-c610-7ab5-9713-99841caf91d0",
    "name": "Itsuking",
    "icon_name": "e56ec3d2-17ac-7603-d08a-f12601dcc5aa.webp",
    "icon_url": "https://2025-bucket.flutterkaigi.jp/staff-members/e56ec3d2-17ac-7603-d08a-f12601dcc5aa.webp",
    "greeting": "Flutterエンジニア目指して転職活動中デス！よろしくお願いします！",
    "sns_links": [
      {
        "type": "x",
        "value": "IamItsuking"
      },
      {
        "type": "github",
        "value": "Ituking"
      }
    ]
  },
  {
    "id": "019a5472-c610-7fa5-ae2c-f4c3e85ba52c",
    "name": "jiyuujin",
    "icon_name": "dbc18436-e245-7c5f-8a11-7510a6567d01.webp",
    "icon_url": "https://2025-bucket.flutterkaigi.jp/staff-members/dbc18436-e245-7c5f-8a11-7510a6567d01.webp",
    "greeting": null,
    "sns_links": [
      {
        "type": "other",
        "value": "https://yuma-kitamura.nekohack.me/"
      },
      {
        "type": "note",
        "value": "uraneko"
      },
      {
        "type": "zenn",
        "value": "jiyuujin"
      },
      {
        "type": "qiita",
        "value": "jiyuujin"
      },
      {
        "type": "medium",
        "value": "jiyuujin"
      },
      {
        "type": "x",
        "value": "jiyuujinlab"
      },
      {
        "type": "github",
        "value": "jiyuujin"
      }
    ]
  },
  {
    "id": "019a5472-c610-74df-a775-62dc775dcd0d",
    "name": "K9i",
    "icon_name": "83b2b2c4-4c28-012f-ceff-c5228859bbd5.webp",
    "icon_url": "https://2025-bucket.flutterkaigi.jp/staff-members/83b2b2c4-4c28-012f-ceff-c5228859bbd5.webp",
    "greeting": "🐙",
    "sns_links": [
      {
        "type": "zenn",
        "value": "k9i"
      },
      {
        "type": "qiita",
        "value": "K9i-0"
      },
      {
        "type": "medium",
        "value": "K9i"
      },
      {
        "type": "x",
        "value": "K9i_apps"
      },
      {
        "type": "github",
        "value": "K9i-0"
      }
    ]
  },
  {
    "id": "019a5472-c610-7723-8024-ae951db8953a",
    "name": "katsuumy",
    "icon_name": "070f9970-08dd-27d4-d80e-14c2c3236436.webp",
    "icon_url": "https://2025-bucket.flutterkaigi.jp/staff-members/070f9970-08dd-27d4-d80e-14c2c3236436.webp",
    "greeting": null,
    "sns_links": [
      {
        "type": "x",
        "value": "katsuumy"
      },
      {
        "type": "github",
        "value": "granoeste"
      }
    ]
  },
  {
    "id": "019a5472-c610-7aac-971e-f702a3e432e2",
    "name": "Keito",
    "icon_name": "0882d1e8-33de-4eb0-9812-0d2274759ac4.webp",
    "icon_url": "https://2025-bucket.flutterkaigi.jp/staff-members/0882d1e8-33de-4eb0-9812-0d2274759ac4.webp",
    "greeting": "個人開発が好きです！",
    "sns_links": [
      {
        "type": "zenn",
        "value": "keito"
      },
      {
        "type": "qiita",
        "value": "kusano_keito"
      },
      {
        "type": "medium",
        "value": "techkeito"
      },
      {
        "type": "x",
        "value": "techkeito"
      },
      {
        "type": "github",
        "value": "keitokusano"
      }
    ]
  },
  {
    "id": "019a5472-c610-76d7-9bfd-4432c77bd6cd",
    "name": "kuno",
    "icon_name": "752792bf-203f-4070-6292-0d468bfd2997.webp",
    "icon_url": "https://2025-bucket.flutterkaigi.jp/staff-members/752792bf-203f-4070-6292-0d468bfd2997.webp",
    "greeting": "盛り上げていきマッショイ！！！！！！！！！！！！！！！",
    "sns_links": [
      {
        "type": "zenn",
        "value": "kuno"
      },
      {
        "type": "x",
        "value": "Kunodayo_oboete"
      },
      {
        "type": "github",
        "value": "kno3a87"
      }
    ]
  },
  {
    "id": "019a5472-c610-7a37-8444-d6bb614441b8",
    "name": "Kurogoma4D",
    "icon_name": "6badf028-a66c-ae43-338b-b162124e6f50.webp",
    "icon_url": "https://2025-bucket.flutterkaigi.jp/staff-members/6badf028-a66c-ae43-338b-b162124e6f50.webp",
    "greeting": "アプリつくります",
    "sns_links": [
      {
        "type": "other",
        "value": "https://krgm4d.dev"
      },
      {
        "type": "zenn",
        "value": "kurogoma4d"
      },
      {
        "type": "x",
        "value": "Krgm4D"
      },
      {
        "type": "github",
        "value": "Kurogoma4D"
      }
    ]
  },
  {
    "id": "019a5472-c610-7dd9-b406-1333e8ebdb1b",
    "name": "masa-futa",
    "icon_name": "1a0b5098-0e01-ba22-3a92-a0792b8fb260.webp",
    "icon_url": "https://2025-bucket.flutterkaigi.jp/staff-members/1a0b5098-0e01-ba22-3a92-a0792b8fb260.webp",
    "greeting": "wai wai ٩( 'ω' )و",
    "sns_links": [
      {
        "type": "zenn",
        "value": "masakunn"
      },
      {
        "type": "qiita",
        "value": "masakunn1215"
      },
      {
        "type": "medium",
        "value": "masakunn1215"
      },
      {
        "type": "x",
        "value": "ma12441469"
      },
      {
        "type": "github",
        "value": "masa-futa"
      }
    ]
  },
  {
    "id": "019a738f-4930-7da5-8135-1db483406716",
    "name": "Masahiro Aoki",
    "icon_name": "3062F094-5885-4977-A992-F0EE7F03E324.jpg",
    "icon_url": "https://2025-bucket.flutterkaigi.jp/staff-members/3062F094-5885-4977-A992-F0EE7F03E324.jpg",
    "greeting": "やっぱりFlutterだなぁ。",
    "sns_links": [
      {
        "type": "x",
        "value": "ma_freud"
      }
    ]
  },
  {
    "id": "019a5472-c610-7a4c-a162-f29a8b6b5e5b",
    "name": "minn",
    "icon_name": "cf3a6106-9815-6e08-5f32-7a1fba74c05c.webp",
    "icon_url": "https://2025-bucket.flutterkaigi.jp/staff-members/cf3a6106-9815-6e08-5f32-7a1fba74c05c.webp",
    "greeting": null,
    "sns_links": [
      {
        "type": "zenn",
        "value": "minn"
      },
      {
        "type": "x",
        "value": "minn_flutter"
      },
      {
        "type": "github",
        "value": "kitashio"
      }
    ]
  },
  {
    "id": "019a5472-c610-71a9-b09d-1f5e6a7c9860",
    "name": "m.kosuke",
    "icon_name": "a6b121ee-ff62-b436-d7d4-dd799fd67692.webp",
    "icon_url": "https://2025-bucket.flutterkaigi.jp/staff-members/a6b121ee-ff62-b436-d7d4-dd799fd67692.webp",
    "greeting": "フロサポ🐬",
    "sns_links": [
      {
        "type": "note",
        "value": "shcahill"
      },
      {
        "type": "zenn",
        "value": "mkosuke"
      },
      {
        "type": "qiita",
        "value": "mkosuke"
      },
      {
        "type": "x",
        "value": "kosuke_mtm"
      },
      {
        "type": "github",
        "value": "shcahill"
      }
    ]
  },
  {
    "id": "019a5472-c610-74fd-8f33-927181319f10",
    "name": "offich",
    "icon_name": "8a8d902b-4e5d-41fe-e745-c43e9ef9e408.webp",
    "icon_url": "https://2025-bucket.flutterkaigi.jp/staff-members/8a8d902b-4e5d-41fe-e745-c43e9ef9e408.webp",
    "greeting": "よろしくお願いいたします！",
    "sns_links": [
      {
        "type": "other",
        "value": "https://offich.me"
      },
      {
        "type": "x",
        "value": "offichy"
      },
      {
        "type": "github",
        "value": "offich"
      }
    ]
  },
  {
    "id": "019a5472-c610-7622-8708-0acb68eff99d",
    "name": "okaryo",
    "icon_name": "e86770b3-189b-47fb-55b5-7fc4aeb560d8.webp",
    "icon_url": "https://2025-bucket.flutterkaigi.jp/staff-members/e86770b3-189b-47fb-55b5-7fc4aeb560d8.webp",
    "greeting": "💪☺️👍",
    "sns_links": [
      {
        "type": "medium",
        "value": "okaryo"
      },
      {
        "type": "x",
        "value": "okaryoX"
      },
      {
        "type": "github",
        "value": "okaryo"
      }
    ]
  },
  {
    "id": "019a75bf-fa6d-7085-903f-83ae2901f727",
    "name": "Oshiro H.",
    "icon_name": "0254e48d-cf57-47ab-9657-0856a5761926.webp",
    "icon_url": "https://2025-bucket.flutterkaigi.jp/staff-members/0254e48d-cf57-47ab-9657-0856a5761926.webp",
    "greeting": "Flutter頑張ります！",
    "sns_links": [
      {
        "type": "github",
        "value": "HiroshiOshiro"
      }
    ]
  },
  {
    "id": "019a73df-61d6-7799-94f7-bb5aa290a860",
    "name": "robo (Rie Kanetaka)",
    "icon_name": "68ec1064-9df3-4a1e-b223-87211229d026.png",
    "icon_url": "https://2025-bucket.flutterkaigi.jp/staff-members/68ec1064-9df3-4a1e-b223-87211229d026.png",
    "greeting": "モバイル端末好きのエンジニア",
    "sns_links": [
      {
        "type": "x",
        "value": "cch_robo"
      }
    ]
  },
  {
    "id": "019a5472-c610-719b-93d6-e67221646069",
    "name": "Seiji",
    "icon_name": "80363ab9-42a3-859c-fd3c-a51eca85d32a.webp",
    "icon_url": "https://2025-bucket.flutterkaigi.jp/staff-members/80363ab9-42a3-859c-fd3c-a51eca85d32a.webp",
    "greeting": "わいわい楽しみましょー！",
    "sns_links": [
      {
        "type": "other",
        "value": "https://www.sijis.me/"
      },
      {
        "type": "zenn",
        "value": "seeiji"
      },
      {
        "type": "qiita",
        "value": "se_eiji"
      },
      {
        "type": "x",
        "value": "se_eiji"
      },
      {
        "type": "github",
        "value": "n-seiji"
      }
    ]
  },
  {
    "id": "019a75c2-257a-7a49-bd6b-5a8fa2a3b468",
    "name": "shanonim",
    "icon_name": "586bbd2b-b949-4ac4-b6bf-8638018d6d0e.webp",
    "icon_url": "https://2025-bucket.flutterkaigi.jp/staff-members/586bbd2b-b949-4ac4-b6bf-8638018d6d0e.webp",
    "greeting": null,
    "sns_links": [
      {
        "type": "x",
        "value": "shanonim"
      }
    ]
  },
  {
    "id": "019a5472-c610-784a-ad6f-7bd8afe12cf6",
    "name": "Shohei Ogawa",
    "icon_name": "9a436d27-2d84-7d40-70cf-9bd4dcd557ef.webp",
    "icon_url": "https://2025-bucket.flutterkaigi.jp/staff-members/9a436d27-2d84-7d40-70cf-9bd4dcd557ef.webp",
    "greeting": "ヒトと技術とお酒が好き",
    "sns_links": [
      {
        "type": "zenn",
        "value": "heyhey1028"
      },
      {
        "type": "qiita",
        "value": "heyhey1028"
      },
      {
        "type": "x",
        "value": "heyhey1028"
      },
      {
        "type": "github",
        "value": "heyhey1028"
      }
    ]
  },
  {
    "id": "019a5472-c610-746d-88c5-a5111a0da0a1",
    "name": "Sohichiro/そーちゃん",
    "icon_name": "261f9261-b64e-f717-431d-82f8cce5ca4c.webp",
    "icon_url": "https://2025-bucket.flutterkaigi.jp/staff-members/261f9261-b64e-f717-431d-82f8cce5ca4c.webp",
    "greeting": "今年もやっていき！",
    "sns_links": [
      {
        "type": "note",
        "value": "sohichiro"
      },
      {
        "type": "zenn",
        "value": "sohichiro"
      },
      {
        "type": "qiita",
        "value": "sohichiro"
      },
      {
        "type": "medium",
        "value": "sohichiro"
      },
      {
        "type": "x",
        "value": "sohichiro"
      },
      {
        "type": "github",
        "value": "sohichiro"
      }
    ]
  },
  {
    "id": "019a5472-c610-78fe-9afa-f95d5d2e4efb",
    "name": "sw",
    "icon_name": "8570633d-7a57-fc3d-5d17-a573aa241bf1.webp",
    "icon_url": "https://2025-bucket.flutterkaigi.jp/staff-members/8570633d-7a57-fc3d-5d17-a573aa241bf1.webp",
    "greeting": null,
    "sns_links": [
      {
        "type": "x",
        "value": "s4y_wt"
      }
    ]
  },
  {
    "id": "019a5472-c610-786b-977c-01f78b9523f7",
    "name": "Tommy (Thomas Aquinas)",
    "icon_name": "1e58401f-d515-1ba9-c077-a0f74a3f664f.webp",
    "icon_url": "https://2025-bucket.flutterkaigi.jp/staff-members/1e58401f-d515-1ba9-c077-a0f74a3f664f.webp",
    "greeting": null,
    "sns_links": [
      {
        "type": "x",
        "value": "ThomasS2558"
      }
    ]
  },
  {
    "id": "019a5472-c610-7d4d-8cd9-35211653e6b2",
    "name": "yasuda makoto",
    "icon_name": "aeef0ebd-47e0-41da-9a20-17e5a5609d16.webp",
    "icon_url": "https://2025-bucket.flutterkaigi.jp/staff-members/aeef0ebd-47e0-41da-9a20-17e5a5609d16.webp",
    "greeting": null,
    "sns_links": [
      {
        "type": "x",
        "value": "1234567890kuro"
      }
    ]
  },
  {
    "id": "019a5472-c610-7906-843f-c674be59f1cf",
    "name": "いせりゅー",
    "icon_name": "d5dcb0ae-2138-486d-801d-706e36a45ffb.webp",
    "icon_url": "https://2025-bucket.flutterkaigi.jp/staff-members/d5dcb0ae-2138-486d-801d-706e36a45ffb.webp",
    "greeting": "個人開発で「FoodGram」のアプリを作っています！",
    "sns_links": [
      {
        "type": "note",
        "value": "iseryu"
      },
      {
        "type": "zenn",
        "value": "iseki"
      },
      {
        "type": "qiita",
        "value": "isekiryu"
      },
      {
        "type": "medium",
        "value": "iseryuuuuu3"
      },
      {
        "type": "x",
        "value": "isekiryu"
      },
      {
        "type": "github",
        "value": "iseruuuuu"
      }
    ]
  },
  {
    "id": "019a5472-c610-7f62-ab1d-92ac57df67a0",
    "name": "うめちゃん",
    "icon_name": "a344dd22-91fe-c805-4951-c61133368364.webp",
    "icon_url": "https://2025-bucket.flutterkaigi.jp/staff-members/a344dd22-91fe-c805-4951-c61133368364.webp",
    "greeting": "参加者の皆さんが楽しめる会になるように頑張ります！",
    "sns_links": [
      {
        "type": "other",
        "value": "https://umechanhika.notion.site/903ff47c623343c695ba9d4f5292e9b5"
      },
      {
        "type": "note",
        "value": "umechanhika"
      },
      {
        "type": "zenn",
        "value": "umechanhika"
      },
      {
        "type": "qiita",
        "value": "umechanhika"
      },
      {
        "type": "medium",
        "value": "umechanhika"
      },
      {
        "type": "x",
        "value": "umechanhika"
      },
      {
        "type": "github",
        "value": "umechanhika"
      }
    ]
  },
  {
    "id": "019a5472-c610-72d0-9675-e6dc1b5ccae9",
    "name": "おかやまん",
    "icon_name": "edaa85c5-d9dd-9dad-9516-849059f2d9a4.webp",
    "icon_url": "https://2025-bucket.flutterkaigi.jp/staff-members/edaa85c5-d9dd-9dad-9516-849059f2d9a4.webp",
    "greeting": "開発楽しむ！",
    "sns_links": [
      {
        "type": "note",
        "value": "blendthink"
      },
      {
        "type": "zenn",
        "value": "blendthink"
      },
      {
        "type": "qiita",
        "value": "blendthink"
      },
      {
        "type": "medium",
        "value": "blendthink"
      },
      {
        "type": "x",
        "value": "blendthink"
      },
      {
        "type": "github",
        "value": "blendthink"
      }
    ]
  },
  {
    "id": "019a5472-c610-7c25-8a44-6dcdab804f1d",
    "name": "おはぎ(あきばこ)",
    "icon_name": "23ca6839-077e-6951-a7f3-116efc39442c.webp",
    "icon_url": "https://2025-bucket.flutterkaigi.jp/staff-members/23ca6839-077e-6951-a7f3-116efc39442c.webp",
    "greeting": null,
    "sns_links": [
      {
        "type": "x",
        "value": "a_key_bako"
      },
      {
        "type": "github",
        "value": "akeybako"
      }
    ]
  },
  {
    "id": "019a5472-c610-70f9-b76f-0c0ac12d30db",
    "name": "たっつー",
    "icon_name": "a2c93661-5a16-2213-89c8-e55ff7056e36.webp",
    "icon_url": "https://2025-bucket.flutterkaigi.jp/staff-members/a2c93661-5a16-2213-89c8-e55ff7056e36.webp",
    "greeting": "アプリチーム頑張ります 💪",
    "sns_links": [
      {
        "type": "other",
        "value": "https://tatsutakein.jp/"
      },
      {
        "type": "note",
        "value": "tatsutakein"
      },
      {
        "type": "zenn",
        "value": "tatsutakein"
      },
      {
        "type": "qiita",
        "value": "tatsutakein"
      },
      {
        "type": "medium",
        "value": "tatsutakein"
      },
      {
        "type": "x",
        "value": "tatsutakein"
      },
      {
        "type": "github",
        "value": "tatsutakein"
      }
    ]
  },
  {
    "id": "019a5472-c610-7bdb-a010-b9d2782b91f0",
    "name": "ちっぴー",
    "icon_name": "faac06be-6646-90fe-d3c2-db95783ffa8a.webp",
    "icon_url": "https://2025-bucket.flutterkaigi.jp/staff-members/faac06be-6646-90fe-d3c2-db95783ffa8a.webp",
    "greeting": "アプリの人として頑張ります。",
    "sns_links": [
      {
        "type": "zenn",
        "value": "chippy"
      },
      {
        "type": "medium",
        "value": "chippy-ao"
      },
      {
        "type": "x",
        "value": "chippy_ao"
      },
      {
        "type": "github",
        "value": "chippy-ao"
      }
    ]
  },
  {
    "id": "019a5472-c610-7483-b47c-82fe8430667b",
    "name": "トマト",
    "icon_name": "81485592-4ddf-4e95-8604-700749d50e81.webp",
    "icon_url": "https://2025-bucket.flutterkaigi.jp/staff-members/81485592-4ddf-4e95-8604-700749d50e81.webp",
    "greeting": "医療系アプリのエンジニアやってます！よろしくお願いします！！",
    "sns_links": [
      {
        "type": "zenn",
        "value": "tomato1"
      },
      {
        "type": "qiita",
        "value": "kagura1"
      },
      {
        "type": "x",
        "value": "1234568aasobso1"
      },
      {
        "type": "github",
        "value": "tomoki1590"
      }
    ]
  },
  {
    "id": "019a5472-c610-7e4a-9f41-964aa0a332e2",
    "name": "のり",
    "icon_name": "1ea6d5c4-29bd-393b-85fa-f977273eb0d4.webp",
    "icon_url": "https://2025-bucket.flutterkaigi.jp/staff-members/1ea6d5c4-29bd-393b-85fa-f977273eb0d4.webp",
    "greeting": "よろしくお願いします🏃",
    "sns_links": [
      {
        "type": "x",
        "value": "no_main_"
      }
    ]
  },
  {
    "id": "019a5472-c610-7b05-aa80-a3cc6a0f3053",
    "name": "もぐもぐ",
    "icon_name": "2fd456f6-20e9-0733-883d-6b25b82f75c5.webp",
    "icon_url": "https://2025-bucket.flutterkaigi.jp/staff-members/2fd456f6-20e9-0733-883d-6b25b82f75c5.webp",
    "greeting": "2025年もよろしくお願いします!",
    "sns_links": [
      {
        "type": "other",
        "value": "https://yumnumm.dev"
      },
      {
        "type": "zenn",
        "value": "YumNumm"
      },
      {
        "type": "qiita",
        "value": "YumNumm"
      },
      {
        "type": "medium",
        "value": "YumNumm"
      },
      {
        "type": "x",
        "value": "YumNumm"
      },
      {
        "type": "github",
        "value": "YumNumm"
      }
    ]
  },
  {
    "id": "019a5472-c610-742b-bf97-41f1ffc432b1",
    "name": "ゆう",
    "icon_name": "e0fbf05e-371e-ad98-c50f-8b26c0752690.webp",
    "icon_url": "https://2025-bucket.flutterkaigi.jp/staff-members/e0fbf05e-371e-ad98-c50f-8b26c0752690.webp",
    "greeting": "よろしくお願いいたします！",
    "sns_links": [
      {
        "type": "x",
        "value": "yu_s1127"
      },
      {
        "type": "github",
        "value": "yu-s1127"
      }
    ]
  },
  {
    "id": "019a5472-c611-720e-a38c-05657fb1e832",
    "name": "よう",
    "icon_name": "a061da27-0670-a4aa-03c5-5217961d62dc.webp",
    "icon_url": "https://2025-bucket.flutterkaigi.jp/staff-members/a061da27-0670-a4aa-03c5-5217961d62dc.webp",
    "greeting": "盛り上げたい！",
    "sns_links": [
      {
        "type": "zenn",
        "value": "yoyoh"
      },
      {
        "type": "qiita",
        "value": "yoyoh_"
      },
      {
        "type": "x",
        "value": "yoyoh_"
      },
      {
        "type": "github",
        "value": "KobayashiYoh"
      }
    ]
  },
  {
    "id": "019a5472-c610-750f-bf4f-09ced58970e6",
    "name": "白崎 紀充",
    "icon_name": "bdfd4ab5-5411-6740-b046-78fdcdde9e7b.webp",
    "icon_url": "https://2025-bucket.flutterkaigi.jp/staff-members/bdfd4ab5-5411-6740-b046-78fdcdde9e7b.webp",
    "greeting": null,
    "sns_links": [
      {
        "type": "x",
        "value": "magnet_0113_eng"
      },
      {
        "type": "github",
        "value": "magnet-0113-eng"
      }
    ]
  },
  {
    "id": "019a5472-c611-7b8d-8920-ffa350bd0c75",
    "name": "菊池紘",
    "icon_name": "45a33db6-15ef-ce51-2f84-60a7a0fb0286.webp",
    "icon_url": "https://2025-bucket.flutterkaigi.jp/staff-members/45a33db6-15ef-ce51-2f84-60a7a0fb0286.webp",
    "greeting": "楽しいFlutterKaigiにしよう！",
    "sns_links": [
      {
        "type": "zenn",
        "value": "kikuchy"
      },
      {
        "type": "qiita",
        "value": "kikuchy"
      },
      {
        "type": "x",
        "value": "kikuchy"
      },
      {
        "type": "github",
        "value": "kikuchy"
      }
    ]
  },
  {
    "id": "019a75be-f26f-7ae1-820d-bf09672727ad",
    "name": "馬渡慎之助",
    "icon_name": "485a62c6-11bf-43c1-92e6-c0e121729ddd.webp",
    "icon_url": "https://2025-bucket.flutterkaigi.jp/staff-members/485a62c6-11bf-43c1-92e6-c0e121729ddd.webp",
    "greeting": "ウオー🔥",
    "sns_links": [
      {
        "type": "x",
        "value": "hensyunoouma"
      }
    ]
  }
]
''';
