// ignore_for_file: avoid_print

import 'dart:convert';
import 'dart:io';

import 'package:bff_client/bff_client.dart';
import 'package:dio/dio.dart';

/// ビルド時にBFF APIからスタッフメンバー情報を取得して、
/// JSONファイルとして生成するスクリプト
Future<void> main() async {
  // 環境変数からBFF_BASE_URLを取得、なければデフォルト値（prod）を使用
  const defaultBffBaseUrl = 'https://2025-bff.flutterkaigi.jp/v1';
  final bffBaseUrl = Platform.environment['BFF_BASE_URL'] ?? defaultBffBaseUrl;

  if (bffBaseUrl.isEmpty) {
    stderr.writeln('Error: BFF_BASE_URL is empty');
    exit(1);
  }

  print('Fetching staff members from: $bffBaseUrl');

  // BFFクライアントの初期化（認証なし）
  final dio = Dio(BaseOptions(baseUrl: bffBaseUrl));
  final apiClient = BffApiClient(dio: dio);

  try {
    // スタッフメンバー一覧を取得
    final staffMembers = await apiClient.v1.staffMembers.getStaffMembers();

    print('Fetched ${staffMembers.length} staff members');

    // JSONファイルとして生成
    final jsonData = staffMembers.map((e) => e.toJson()).toList();

    final jsonOutput = const JsonEncoder.withIndent('  ').convert(jsonData);

    // JSONファイルに書き込み
    final jsonFile = File('lib/src/config/staffs_data.json');
    await jsonFile.writeAsString(jsonOutput);
    print('Generated: ${jsonFile.path}');

    // Dartファイルとして JSON文字列を定義
    final dartContent =
        '''
// GENERATED FILE - DO NOT EDIT
// This file is generated by tool/fetch_staffs.dart

/// スタッフメンバーデータのJSON文字列
/// ignore: unnecessary_raw_strings
const String staffsDataJson = r\'\'\'
$jsonOutput
\'\'\';
''';

    final dartFile = File('lib/src/config/staffs_data.json.dart');
    await dartFile.writeAsString(dartContent);
    print('Generated: ${dartFile.path}');

    print('Done!');
    // ignore: avoid_catches_without_on_clauses
  } catch (e, stackTrace) {
    stderr.writeln('Error fetching staff members: $e');
    stderr.writeln(stackTrace);
    exit(1);
  }
}
